# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION_ = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION_) do |config|
  config.vm.provision :shell, :path => File.join(File.dirname(__FILE__), "bootstrap.sh") , :args => File.basename(Dir.pwd)
  config.vm.synced_folder File.expand_path("~/development/dotfiles"), "/home/vagrant/development/dotfiles", :mount_options => ["ro"]
end
